### PR TITLE
Prepare for npm release process

### PR DESCRIPTION
**Pull request by Nabeelperson**
## Description of the change

Update package file for org name
 - Add shebang for zli install
 - Add repo link in package file
 - Update readme
 - Version update to 4.20.3

https://www.npmjs.com/package/@bastionzero/zli

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Refactor (code change with no functionality change)
- [ ] Enhancement (minor change below the level of a feature)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Remove feature (removes a feature we don't support anymore)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related JIRA tickets

Relates to JIRA: CWC-853

## Relevant release note information

Release Notes:

## Potential Security Impacts

Does this PR have any security impact?
Does it fix a security issue?
Does it add attack surface?
Why do we think this change is safe?

### Development

- [ ] Does the code changed/added as part of this pull request have test coverage?
- [ ] Do all tests related to the changed code pass in development?
- [ ] Have you ensured that at least one other person has tested your code?
- [ ] Have you tested the code?
- [ ] Have you attached any pictures (if relevant)?

### CODE REVIEW

**Comment by Nabeelperson** [comment]
I have tested this preliminarily. Still needs some work to determine automated release process. Jira ticket has some links to release flows. 

To test the install process, just pull this branch and run:

```
npm i -g .
```

**Comment by sidpremkumar** [comment]
How do we do update for this moving forward? Anything like homebrew tap that we need to automate?

**Review by sidpremkumar — APPROVED** [review]
Tested and worked as expected
```
➜  zli git:(feat/npm-package) ✗ npm i -g .
/Users/sidpremkumar/.nvm/versions/node/v12.21.0/bin/zli -> /Users/sidpremkumar/.nvm/versions/node/v12.21.0/lib/node_modules/@bastionzero/zli/dist/src/index.js
npm WARN notsup Unsupported engine for @bastionzero/zli@4.20.3: wanted: {"node":">0.12.0","npm":">7.0.0"} (current: {"node":"12.21.0","npm":"6.14.11"})
npm WARN notsup Not compatible with your version of node/npm: @bastionzero/zli@4.20.3
npm WARN @bastionzero/zli@4.20.3 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.

+ @bastionzero/zli@4.20.3
added 3 packages from 2 contributors in 1.948s
➜  zli git:(feat/npm-package) ✗ 
```

**Comment by Nabeelperson** [comment]
@sidpremkumar I added you to the npm group. What you will need to do is generate an API token, and then in the bzero zli release command it will just need to call `npm publish --access public` with that token. The npm command will automatically look at the package.json and figure out the version bump. If you want to be really fancy with tagging the npm releases and so on, take a look at the second article.

https://docs.npmjs.com/cli/v7/commands/npm-publish
https://zellwk.com/blog/publish-to-npm/

**Comment by Nabeelperson** [comment]
As for conflicts with homebrew, of course don't install zli from homebrew and npm. Nothing we can do if they try both. Whatever package manager they run last will take over the zli symlink.

**Comment by Nabeelperson** [comment]
TODO: test `npm run release` generated names.

**Comment by sidpremkumar** [comment]
> @sidpremkumar I added you to the npm group. What you will need to do is generate an API token, and then in the bzero zli release command it will just need to call `npm publish --access public` with that token. The npm command will automatically look at the package.json and figure out the version bump. If you want to be really fancy with tagging the npm releases and so on, take a look at the second article.
> 
> https://docs.npmjs.com/cli/v7/commands/npm-publish
> https://zellwk.com/blog/publish-to-npm/

Okay cool, could you make a ticket and assign it to me and I will get started with that. 

Also, I was referring to the `name` here: https://github.com/bastionzero/zli/pull/120/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R2 and wondering if that was going to cause any issues with brew, it seems like it will not though.

**Comment by Nabeelperson** [comment]
@sidpremkumar the names published do not change, npm release ignores org name.
https://commonwealthcrypto.atlassian.net/browse/CWC-857

**Pull request merged**
