### PR TITLE
Fix dependabot alerts for ansi-regex and set-value

### PR DESCRIPTION
**Pull request by sidpremkumar**
## Description of the change

We have been flagged in our zli repo for our use of outdated set-value and ansi-regex dependencies. We need to update them accordingly. 
"ansi-regex": ">=5.0.1"
"set-value": ">=4.0.1"

Tested by rebuilding and connected to kube target: 
2021-11-04 at 1 42 PM

This has security impact. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Refactor (code change with no functionality change)
- [ ] Enhancement (minor change below the level of a feature)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Remove feature (removes a feature we don't support anymore)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related JIRA tickets

Relates to JIRA: CWC-1251

## Relevant release note information

Release Notes:

## Potential Security Impacts

Does this PR have any security impact?
Does it fix a security issue?
Does it add attack surface?
Why do we think this change is safe?

### Development

- [ ] Does the code changed/added as part of this pull request have test coverage?
- [ ] Do all tests related to the changed code pass in development?
- [ ] Have you ensured that at least one other person has tested your code?
- [x] Have you tested the code?
- [x] Have you attached any pictures (if relevant)?

### CODE REVIEW

**Comment by EthanHeilman** [comment]
Update the PR template to explain that this is a bugfix and that it has security impact

**Review by lipmas — APPROVED** [review]

**Comment by sidpremkumar** [comment]
> Update the PR template to explain that this is a bugfix and that it has security impact

This is not a bugfix , I have updated to say this has security impact.

**Comment by EthanHeilman** [comment]
I mean in the template 
image

**Comment by EthanHeilman** [comment]
I don't see any `set-value` changes in the PR?

**Comment by EthanHeilman** [comment]
And whats the deal with all the `"dev": true` changes?

**Pull request merged**
